---
- name: Setup | get client.cinder ceph keyring
  ansible.builtin.command: ceph auth get-or-create client.cinder
  register: client_cinder_keyring
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup | check if nova user exists
  ansible.builtin.user:
    name: nova
  check_mode: true
  register: is_nova
  become: true

- name: Setup | copy client.cinder ceph keyring
  ansible.builtin.copy:
    content: "{{ client_cinder_keyring.stdout }}\n"
    dest: "/etc/ceph/ceph.client.cinder.keyring"
    owner: "{{ os_service_name }}"
    group: "{{ is_nova.changed | ternary('cinder', 'nova') }}"
    mode: "0640"
  become: true

- name: Setup | get client.cinder-backup ceph keyring
  ansible.builtin.command: ceph auth get-or-create client.cinder-backup
  register: client_cinder_backup_keyring
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup | copy client.cinder-backup ceph keyring
  ansible.builtin.copy:
    content: "{{ client_cinder_backup_keyring.stdout }}\n"
    dest: "/etc/ceph/ceph.client.cinder-backup.keyring"
    owner: "{{ os_service_name }}"
    group: "{{ os_service_name }}"
    mode: "0600"
  become: true
...
