---
- name: Main | import common tasks
  ansible.builtin.import_tasks: "common.yml"

- name: Main | include os specific tasks
  ansible.builtin.include_tasks: "{{ lookup('first_found', _params) }}"
  vars:
    _params:
      files:
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_release | lower }}.yml"
        - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
      paths:
        - "."
  when: inventory_hostname in groups['cinder']

- name: Main | include lvm storage backends
  ansible.builtin.include_tasks: "lvm.yml"
  when: '"lvm" in storage_backends'
  when: inventory_hostname in groups['cinder']

- name: Main | include DB tasks
  ansible.builtin.include_tasks: "db.yml"
  when: inventory_hostname in groups['cinder']

- name: Main | include openstack tasks
  ansible.builtin.include_tasks: "openstack.yml"
  when: inventory_hostname in groups['cinder']

- name: Main | include setup tasks
  ansible.builtin.include_tasks: "setup.yml"
  when: inventory_hostname in groups['cinder']

- name: Main | include lightos storage backends
  ansible.builtin.include_role:
    name: pbos.lightos
  when:
    - inventory_hostname in groups['openstack']
    - '"lightos" in storage_backends'
...
