---
- name: Setup | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0755"
  become: true
  loop: "{{ os_service_init }}"

- name: Setup | create systemd drop-in replacement directory
  ansible.builtin.file:
    path: "/etc/systemd/system/{{ item }}.d"
    state: directory
    owner: "root"
    group: "root"
    mode: "0755"
  become: true
  loop: "{{ os_systemd_service_name }}"

- name: Setup | create systemd drop-in replacement files for KillMode=mixed
  ansible.builtin.copy:
    dest: "/etc/systemd/system/{{ item }}.d/killmode.conf"
    content: |
      [Service]
      KillMode=mixed
    owner: "root"
    group: "root"
    mode: "0644"
  loop: "{{ os_systemd_service_name }}"
  become: true
  notify:
    - openstack systemctl restart service

- name: Setup | reload systemd
  ansible.builtin.command: >-
    systemctl daemon-reload
  become: true

- name: Setup | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "{{ os_service_name }}"
    mode: "0640"
    backup: true
  loop: "{{ os_service_conf }}"
  become: true
  changed_when: true
  notify:
    - openstack systemctl restart service

- name: Setup | include ceph cinder keyring task
  ansible.builtin.include_tasks: ceph_cinder_keyring.yml
  when: '"ceph" in storage_backends'

- name: Setup | populate database
  ansible.builtin.shell: su -s /bin/sh  -c "cinder-manage db sync" cinder
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup | flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup | start haproxy service
  ansible.builtin.service:
    name: "haproxy.service"
    state: "started"
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Setup | check service is available
  ansible.builtin.uri:
    url: "{{ os_service_url }}"
    method: GET
    timeout: 3
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true
  failed_when: false
  register: _result
  until: _result.status == 300
  retries: 5
  delay: 5

- name: Setup | create volume type
  ansible.builtin.include_tasks: volume_type.yml
  loop: "{{ storage_backends }}"
...
