---
- name: Setup | copy init file
  ansible.builtin.copy:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest }}"
    owner: "root"
    group: "root"
    mode: "0755"
  become: true
  loop: "{{ os_service_init }}"

- name: Setup | template configuration
  ansible.builtin.template:
    dest: "{{ item.dest }}"
    src: "{{ ansible_os_family | lower }}{{ item.dest + '.j2' }}"
    owner: "root"
    group: "{{ os_service_name }}"
    mode: "0640"
    backup: true
  loop: "{{ os_service_conf }}"
  become: true
  changed_when: true
  notify:
    - openstack systemctl restart service

- name: Setup | populate database
  ansible.builtin.shell: su -s /bin/sh  -c "cinder-manage db sync" cinder
  become: true
  delegate_to: "{{ groups['cinder'][0] }}"
  run_once: true

- name: Setup | flush handlers
  ansible.builtin.meta: flush_handlers

- name: Setup | start haproxy service
  ansible.builtin.service:
    name: "haproxy.service"
    state: "started"
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Setup | include ceph cinder keyring task
  ansible.builtin.include_tasks: ceph_cinder_keyring.yml
  when: '"ceph" in storage_backends'
...
