---
- name: "Setup | check if volume type {{ item }} exists"
  ansible.builtin.shell: >-
    . {{ ansible_env.HOME }}/.adminrc &&
    openstack volume type show -c id -f value {{ item }}
  register: _is_vol_type
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  failed_when: _is_vol_type.rc not in [0, 1]

- name: "Setup | set volume type {{ item }} to Private if it exists"
  ansible.builtin.shell: >-
    . {{ ansible_env.HOME }}/.adminrc &&
    cinder type-update --is-public False {{ _is_vol_type.stdout }}
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  register: _result
  until: _result.rc == 0
  retries: 3
  delay: 3
  when: _is_vol_type.rc == 0

- name: "Setup | create volume type {{ item }}"
  ansible.builtin.shell: >-
    . {{ ansible_env.HOME }}/.adminrc &&
    openstack volume type create --private \
      --property volume_backend_name={{ item }} {{ item }}
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  register: _result
  until: _result.rc == 0
  retries: 3
  delay: 3
  when: _is_vol_type.rc == 1
...
