---
- name: "OpenStack | check if volume type {{ item }} exists"
  ansible.builtin.shell: >-
    . {{ ansible_env.HOME }}/.adminrc &&
    openstack volume type show {{ item }}
  register: _is_vol_type
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  failed_when: _is_vol_type.rc not in [0, 1]

- name: "OpenStack | create volume type {{ item }}"
  ansible.builtin.shell: >-
    . {{ ansible_env.HOME }}/.adminrc &&
    openstack volume type create \
      --property volume_backend_name={{ item }} {{ item }}
  delegate_to: "{{ groups['controller'][0] }}"
  run_once: true
  when: _is_vol_type.rc == 1
...
