---
- name: openstack systemctl restart service
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  loop: "{{ os_systemd_service_name }}"

- name: lvm systemctl restart service
  ansible.builtin.service:
    name: "{{ item }}"
    state: "restarted"
    enabled: true
  register: _restart_service
  until: _restart_service.state == "started"
  retries: 3
  delay: 3
  become: true
  loop: "{{ lvm_systemd_service_name }}"

- name: pbos-lvm systemctl enable service
  ansible.builtin.systemd:
    name: "{{ item }}"
    daemon-reload: true
    enabled: true
  become: true
  loop: "{{ pbos_lvm_systemd_service_name }}"
...
